# Generated by Django 3.0 on 2021-01-09 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20210109_1053'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieLinks',
            new_name='MovieLink',
        ),
    ]
