# Generated by Django 3.0 on 2021-01-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_auto_20210111_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('hollywood', 'HOLLYWOOD'), ('bollywood', 'BOLLYWOOD'), ('tamil', 'TAMIL'), ('foreign', 'FOREIGN'), ('chainese', 'CHAINESE')], default='', max_length=15),
            preserve_default=False,
        ),
    ]
